// <auto-generated />
using System;
using Bricker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bricker.Api.Data.Migrations
{
    [DbContext(typeof(BrickerDbContext))]
    partial class BrickerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bricker.Api.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9473e2aa-0fa8-4e01-b2cf-99781af54c01"),
                            IsActive = true,
                            Name = "Revestimentos",
                            Slug = "revestimentos"
                        },
                        new
                        {
                            Id = new Guid("9473e2aa-0fa8-4e01-b2cf-99781af54c02"),
                            IsActive = true,
                            Name = "Madeira",
                            Slug = "madeira"
                        },
                        new
                        {
                            Id = new Guid("9473e2aa-0fa8-4e01-b2cf-99781af54c03"),
                            IsActive = true,
                            Name = "Hidráulica",
                            Slug = "hidraulica"
                        },
                        new
                        {
                            Id = new Guid("9473e2aa-0fa8-4e01-b2cf-99781af54c04"),
                            IsActive = true,
                            Name = "Elétrica",
                            Slug = "eletrica"
                        },
                        new
                        {
                            Id = new Guid("9473e2aa-0fa8-4e01-b2cf-99781af54c05"),
                            IsActive = true,
                            Name = "Ferragens",
                            Slug = "ferragens"
                        });
                });

            modelBuilder.Entity("Bricker.Api.Models.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Condition")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SellerDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Status", "CategoryId", "City", "State");

                    b.ToTable("Listings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a304bbca-6477-4490-957b-10bc19e7ca01"),
                            CategoryId = new Guid("9473e2aa-0fa8-4e01-b2cf-99781af54c01"),
                            City = "Itajaí",
                            Condition = 0,
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lote excedente de porcelanato acetinado, armazenado em local coberto.",
                            Price = 42m,
                            Quantity = 18m,
                            RowVersion = new byte[0],
                            SellerDisplayName = "Construtora local",
                            State = "SC",
                            Status = 1,
                            Title = "Porcelanato cinza 60 x 60",
                            Unit = "m²"
                        },
                        new
                        {
                            Id = new Guid("a304bbca-6477-4490-957b-10bc19e7ca02"),
                            CategoryId = new Guid("9473e2aa-0fa8-4e01-b2cf-99781af54c02"),
                            City = "Balneário Camboriú",
                            Condition = 0,
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portas novas, sem uso, excedentes de reforma residencial.",
                            Price = 380m,
                            Quantity = 3m,
                            RowVersion = new byte[0],
                            SellerDisplayName = "Marcenaria parceira",
                            State = "SC",
                            Status = 1,
                            Title = "Portas de madeira maciça",
                            Unit = "unidade"
                        },
                        new
                        {
                            Id = new Guid("a304bbca-6477-4490-957b-10bc19e7ca03"),
                            CategoryId = new Guid("9473e2aa-0fa8-4e01-b2cf-99781af54c01"),
                            City = "Navegantes",
                            Condition = 1,
                            CreatedAtUtc = new DateTime(2026, 8, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tijolos de solo-cimento disponíveis para retirada no local.",
                            Price = 1.25m,
                            Quantity = 800m,
                            RowVersion = new byte[0],
                            SellerDisplayName = "Obra residencial",
                            State = "SC",
                            Status = 1,
                            Title = "Tijolo ecológico",
                            Unit = "unidade"
                        });
                });

            modelBuilder.Entity("Bricker.Api.Models.Listing", b =>
                {
                    b.HasOne("Bricker.Api.Models.Category", "Category")
                        .WithMany("Listings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Bricker.Api.Models.Category", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
